export const LOAD_REPORTS_SUCCESS = "LOAD_REPORTS_SUCCESS"
export const LOAD_REPORTS_REQUEST = "LOAD_REPORTS_REQUEST"
export const LOAD_REPORTS_FAIL = "LOAD_REPORTS_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"

 