export const LIKELIHOOD_SORT_START = "LIKELIHOOD_SORT_START"
export const LIKELIHOOD_SORT_END = "LIKELIHOOD_SORT_END"



export const REGIONAL_MAP_MAKING_START = "REGIONAL_MAP_MAKING_START"
export const REGIONAL_MAP_MAKING_END = "REGIONAL_MAP_MAKING_END"
export const REGIONAL_SORT_START = "REGIONAL_SORT_START"
export const REGIONAL_SORT_END = "REGIONAL_SORT_END"



export const COUNTRY_MAP_MAKING_START = "COUNTRY_MAP_MAKING_START"
export const COUNTRY_MAP_MAKING_END = "COUNTRY_MAP_MAKING_END"
export const COUNTRY_SORT_START = "COUNTRY_SORT_START"
export const COUNTRY_SORT_END = "COUNTRY_SORT_END"



export const PESTAL_MAP_MAKING_START = "PESTAL_MAP_MAKING_START"
export const PESTAL_MAP_MAKING_END = "PESTAL_MAP_MAKING_END"
export const PESTAL_SORT_START = "PESTAL_SORT_START"
export const PESTAL_SORT_END = "PESTAL_SORT_END"



export const TOPIC_MAP_MAKING_START = "TOPIC_MAP_MAKING_START"
export const TOPIC_MAP_MAKING_END = "TOPIC_MAP_MAKING_END"