export const LOAD_USER_SUCCESS = "LOAD_USER_SUCCESS"
export const LOAD_USER_REQUEST = "LOAD_USER_REQUEST"
export const LOAD_USER_FAIL = "LOAD_USER_FAIL"

export const LOAD_more_USER_SUCCESS = "LOAD_more_USER_SUCCESS"
export const LOAD_more_USER_REQUEST = "LOAD_more_USER_REQUEST"
export const LOAD_more_USER_FAIL = "LOAD_more_USER_FAIL"

export const CLEAR_ERROR = "CLEAR_ERROR"

export const SET_SELECTED_USER_INDEX = "SET_SELECTED_USER_INDEX"
 